language: generic
sudo: required # super user permissions

services:
  - docker
 
before_install:
  - docker build -t hades12/docker-client-test -f ./client/Dockerfile.dev ./client
   
script:
  - docker run -e CI=true hades12/docker-client-test npm test
  
after_success:
  - docker build -t hades12/docker-complex-test-client ./client
  - docker build -t hades12/docker-complex-test-server ./server
  - docker build -t hades12/docker-complex-test-worker ./worker
  - docker build -t hades12/docker-complex-test-nginx ./nginx  
  # docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  # push images 
  - docker push hades12/docker-complex-test-client
  - docker push hades12/docker-complex-test-server
  - docker push hades12/docker-complex-test-worker
  - docker push hades12/docker-complex-test-nginx

# deploy:
 # edge: true
 # provider: elasticbeanstalk
 # region: "us-east-2"
 # app: "docker"
 # env: "docker-env"
 # bucket_name: "elasticbeanstalk-us-east-2-923445559289"
 # bucket_path: "docker"
 # on:
   # branch: master
 # access_key_id: $aws_access_key
 # secret_access_key: $aws_secret_key